export const HEADLINE_1_MULTIPLIERS = {
  NAME: 'Headline 1',
  SIZE_MIN: 0.8,
  SIZE_MAX: 1.2,
  SPACING_BOTTOM_MAX: 1.7,
  SPACING_BOTTOM_MIN: 1,
  SPACING_TOP_MAX: 2.7,
  SPACING_TOP_MIN: 2
}

export const HEADLINE_2_MULTIPLIERS = {
  NAME: 'Headline 2',
  SIZE_MIN: 0.8,
  SIZE_MAX: 1.2,
  SPACING_BOTTOM_MAX: 1.5,
  SPACING_BOTTOM_MIN: 0.8,
  SPACING_TOP_MAX: 2.2,
  SPACING_TOP_MIN: 1.8
}

export const HEADLINE_3_MULTIPLIERS = {
  NAME: 'Headline 3',
  SIZE_MIN: 0.9,
  SIZE_MAX: 1.1,
  SPACING_BOTTOM_MAX: 0.7,
  SPACING_BOTTOM_MIN: 0.3,
  SPACING_TOP_MAX: 1.7,
  SPACING_TOP_MIN: 1.3
}
