export const SCOPES = {
  NATIVE_APP: 'NATIVE_APP',
  WEBSITE: 'WEBSITE',
  TEXT_DOCUMENT: 'TEXT_DOCUMENT',
  IOS: 'IOS',
  ANDROID: 'ANDROID',
  RESPONSIVE: 'RESPONSIVE',
  NOT_RESPONSIVE: 'NOT_RESPONSIVE',
  PAPER: 'PAPER',
  DISPLAY: 'DISPLAY',
  PAPER_DISPLAY: 'PAPER_DISPLAY'
}
